### PR TITLE
NO-ISSUE: Remove local manifests

### PR DESCRIPTION
**Pull request by stephenfin**
Nothing in here is used. Instead, we use the manifests provided by the Cluster Storage Operator [1]. As a result there has been significant divergence with patches that are only present in the CSO manifests and, more significantly, a patch that is only present here (commit 660bbb77).

Resolve the source of confusion by removing these manifests and updating the README to make it clear that the Cluster Storage Operator (CSO) is responsible for configuring this operator nowadays.

[1] https://github.com/openshift/cluster-storage-operator/tree/master/assets/csidriveroperators/manila

Signed-off-by: Stephen Finucane <stephenfin@redhat.com>

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
I wonder if the reason is that the local manifest were used for deploying the operator during development... anyway, I also think we should remove them if there are not used.

Have you checked that both are functionally equivalent? For instance, I can see that https://github.com/openshift/csi-driver-manila-operator/commit/660bbb775b09eefc7df4ec9587b70d657f7d31ff updated the manifest but I can't find a corresponding commit for CSO.

**Comment by stephenfin** [comment]
> I wonder if the reason is that the local manifest were used for deploying the operator during development... anyway, I also think we should remove them if there are not used.
> 
> Have you checked that both are functionally equivalent? For instance, I can see that [660bbb7](https://github.com/openshift/csi-driver-manila-operator/commit/660bbb775b09eefc7df4ec9587b70d657f7d31ff) updated the manifest but I can't find a corresponding commit for CSO.

I opened https://github.com/openshift/cluster-storage-operator/pull/412 to close this gap. That unmerged PR was the motivation for closing this.

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
