### PR TITLE
DO NOT MERGE - CI testing

### PR DESCRIPTION
**Pull request by EmilienM**

### CODE REVIEW

**Comment by EmilienM** [comment]
```
event happened 22 times, something is wrong: ns/e2e-volumemode-5438 persistentvolumeclaim/pvc-z5gv2 - reason/ExternalProvisioning waiting for a volume to be created, either by external provisioner "manila.csi.openstack.org" or manually created by system administrator
```

/retest

**Comment by jsafrane** [comment]
Hmm, maybe we need to ask to for exception for this event. All dynamic provisioning in a CSI driver will produce such event.

**Pull request closed without merging**
