### PR TITLE
Use go:embed for static yaml files #179

### PR DESCRIPTION
**Pull request by jsafrane**
Move from bindata to go:embed.

Contains bump of library-go and related changes.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for https://github.com/openshift/library-go/pull/1117

**Comment by jsafrane** [comment]
/hold cancel
updated with openshift/library-go#1117

**Comment by mandre** [comment]
Let's give the [shiny new Manila CSI job](https://github.com/openshift/release/pull/19179/) a spin
/retest

**Review by mandre — COMMENTED** [review]
/lgtm
/hold for CI

**Comment by jsafrane** [comment]
Not sure what's the magic CI command to run new tests...
/refresh

**Comment by mandre** [comment]
Hmm, come on you can do it.
/test e2e-openstack-csi

**Comment by jsafrane** [comment]
This looks like genuine failure, I don't see NFS driver DaemonSet.

**Review by mandre — COMMENTED** [review]
CI FTW!

/lgtm

@jsafrane please remove the hold at your convenience.

**Pull request merged**
