### PR TITLE
Bug OCPBUGS-944: Fix RBAC race during initial deployment

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
The library-go bump isn't necessary for this PR, but since we need to bump it anyway, I'm tagging this PR.

/lgtm

**Comment by mdbooth** [comment]
Looks like the test failure was due to https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/202 which has now merged.

/retest-required

**Comment by mandre** [comment]
We're seeing the same problem in 4.11: https://issues.redhat.com/browse/OCPBUGS-8067
/cherry-pick release-4.11

**Comment by mandre** [comment]
Great, there's a library-go bump that prevents backporting the patch via automated tooling. Will have to backport manually.

**Pull request merged**
