### PR TITLE
Bug 1988506: Backport e2e testing

### PR DESCRIPTION
**Pull request by EmilienM**
This is a combined & clean cherry-pick to backport e2e testing into 4.8.

## Add e2e manifest for testing
- Add test/e2e/manifest.yaml which will be used to run the test suite.
- Add e2e.sh script to run the tests (helper).

## test/e2e/manifest: hardcode StorageClass
The Storage Class is generated by the Manila CSI Operator, based on available
share types that have been created in Manila. For CI purpose, we assume
that a "default" share type exists and will be used for the StorageClass.
If you run this manifest against an OpenStack cloud where there is no "default" share type,
you'll need to change the value.

##  Create CI image for Manila CSI Operator testing
Add a basic Dockerfile.test that was largely inspired by the one in the
Cinder CSI operator.
We also had to change the .gitignore to remove "*.text" entry.

[OSASINFRA-2603](https://issues.redhat.com/browse/OSASINFRA-2603)

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Comment by udis** [comment]
lgtm

No further tests are needed from QE

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
