### PR TITLE
 Bug 1948090: Deploy multiple replicas of CSI Controller Service

### PR DESCRIPTION
**Pull request by bertinatto**
Currently, we deploy only one replica of the CSI Controller Service Deployment. This apparently leads to the operator going unavailable when draining the node where the Deployment is running on. Also, since we use the RollingUpdate strategy, Deployment rollous get stuck in single-node clusters because the new pod waits for a node with free ports, which never happens because the old pod is waiting for the new pod to start.

This patch uses the hook introduced in openshift/library-go#1056 to run multiple replicas of the operand, i.e., 1 in single-node control-planes or 2 in multiple-node control-planes. In addition to that, we set maxSurge=0 and maxUnavailable=1 in the RollingUpdate strategy to make sure pods are drained one at a time and to prevent more than one pod (same operand) running at the same time in the node, since we use nodePorts and hostNetwork in this operator. Also, we set anti-affinity rules to avoid two replicas running on the same master node.

Finally, I add a commit to create a PDB in order to prevent all CSI Controller Service replicas going unavailable.

CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Installation failed with:

`
                        "message": "ManilaCSIDriverOperatorCRDegraded: ManilaDriverControllerServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: ManilaDriverNodeServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: NFSDriverNodeServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: ResourceSyncControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: SecretSyncDegraded: namespaces \"openshift-manila-csi-driver\" not found",
`

**Comment by bertinatto** [comment]
> Installation failed with:
> 
> `"message": "ManilaCSIDriverOperatorCRDegraded: ManilaDriverControllerServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: ManilaDriverNodeServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: NFSDriverNodeServiceControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: ResourceSyncControllerDegraded: namespaces \"openshift-manila-csi-driver\" not found\nManilaCSIDriverOperatorCRDegraded: SecretSyncDegraded: namespaces \"openshift-manila-csi-driver\" not found",`

This seems unrelated to this PR. I also see this message:

```
E0803 13:51:10.025090  630515 static_resource_controller.go:122] cannot decode "volumesnapshotclass.yaml": no kind "VolumeSnapshotClass" is registered for version "snapshot.storage.k8s.io/v1" in scheme "pkg/runtime/scheme.go:100"
```

**Comment by jsafrane** [comment]
CI looks good, Manila excessive events are tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1990190

**Pull request merged**
