### PR TITLE
Bug 2038053: Bump k8s to 1.23

### PR DESCRIPTION
**Pull request by mandre**
This is the result of:
```
go get github.com/openshift/api@7c47a5f
go get github.com/openshift/client-go@7385dd6
go get github.com/openshift/library-go@624c91f
go get k8s.io/component-base@969bfa2
go mod vendor
go mod tidy
```

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/hold
see https://bugzilla.redhat.com/show_bug.cgi?id=2038166

**Comment by sdodson** [comment]
/hold
This also missed feature freeze. We need to discuss whether or not these make sense to land after feature freeze.

**Pull request merged**
